inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 21

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
